### ISSUE TITLE
GUI freeze and doesn't respond

### ISSUE THREAD

**Issue by uncle-yura** [mbuesch/awlsim#26]
On Windows, the system works as usual, but on Linux the Avlsim interface freezes. If you do not press the disconnect button, then everything also works as usual.

Steps to reproduce the issue:
1. Press server connection button and start simulator core.
2. Press server connection button to disconect.
3. Close window or press exit button.
4. ...
```
AwlSimServer: [2.304] Received message: RUNSTATE 0
awlsim-gui: [5.546] AwlSimClient: Received message 0x0000
AwlSimServer: [2.305] Client '[127.0.0.1]:36058' disconnected
AwlSimServer: [5.212] Received signal 15
AwlSimServer: [5.213] Switched to AUTO garbage collection.
```

**Comment by mbuesch** [comment]
Thanks for the report.
I'm currently rewriting the connection/runstate handling code. It's very old code that essentially dates back to the first releases. So it contains lots of hacks.
So I'll try to find out what's going on while rewriting that code.
