### ISSUE TITLE
Non-English names are not displayed in the compiler window

### ISSUE THREAD

**Issue by uncle-yura** [mbuesch/awlsim#27]
Non-English names are not displayed in the compiler window. 
Instead of words it turns out "____".

```
// 
// FUNCTION generated by Awlsim FUP compiler
// 
// Source            : 123 ____ 
// Compiler version  : 0.73.0-pre
// AWL mnemonics     : DE (German)
// Optimizers        : grid-1: biefwd, lblrem, noprem
// 
FUNCTION FC 1 : VOID
	TITLE   = 123 ____ 
	FAMILY  : FUP
	VERSION : 0.73.0-pre
BEGIN
        BE;
END_FUNCTION
```

**Comment by mbuesch** [comment]
Thanks for your report.

This behaviour actually is on purpose.
AWL/STL sources are Latin1 encoded to be S7 compatible. So any non-Latin1 character in freetext fields (like names, titles or comments) is substituted.
