### ISSUE TITLE
import *

### ISSUE THREAD

**Issue by MarkusHackspacher** [mbuesch/awlsim#3]
Congratulations to your project, it is well done.

But I noticed that as many import * there, which has a reason?
https://github.com/mbuesch/awlsim/blob/master/awlsim/core/cpu.py#L34-L55
For me looks without * better, for example:

    from awlsim.common.cpuspecs import S7CPUSpecs

**Comment by mbuesch** [comment]
Thanks for your opinion.

I'd like to rephrase the question a bit: Why not to use import *?
Yes, it uses a bit more memory and it might make awlsim a milliseconds slower to start up, but it simplifies the code a lot. As you can see in your example we already have tons of imports. Importing each symbol individually doesn't improve the situation.

**Comment by MarkusHackspacher** [comment]
Has the disadvantage that existing objects (functions, classes etc.) can be unnoticed overwritten.

If somebody make in blocks.py a class DB, and in the datablock.py is already a class DB, than python use the class DB from the last import. And somebody change a year later the order of the imports and the program not works, but nobody know why.

Should I make a example and send a request?

**Comment by mbuesch** [comment]
>Should I make a example and send a request?

No thanks. I know very well, how the Python import mechanism works. :)

And my answer is: Don't make two DB classes then. Awlsim is supposed to be one single name space. Even if non-wildcard-imports were used, it would be _really_ confusing to have two classes with the same name.
Short answer: Just don't do that.
