### ISSUE TITLE
AWL translation issues

### ISSUE THREAD

**Issue by MichaelWoodc** [mbuesch/awlsim#30]
I am not sure what to do about these issues, I'd like to use the AWL file as is but it is from the 90's and I'm not sure what may have changed since then.  I've attached screenshots and the original AWL file

![Screen Shot 06-11-21 at 07 09 PM 52](https://user-images.githubusercontent.com/51295010/122405564-27f99980-cf4e-11eb-8f90-642ae7ccd3f3.JPG)
![Screen Shot 06-11-21 at 07 14 PM 25](https://user-images.githubusercontent.com/51295010/122405567-28923000-cf4e-11eb-888f-d7849dfa2dd0.JPG)
![Screen Shot 06-10-21 at 06 05 PM 20](https://user-images.githubusercontent.com/51295010/122405570-28923000-cf4e-11eb-888d-56d62a888dc8.JPG)
[mill55awl.txt](https://github.com/mbuesch/awlsim/files/6670534/mill55awl.txt)

**Comment by mbuesch** [comment]
Thanks for your questions.
A label in AWL can have up to 4 characters (excluding the colon).
So you would have to change your label `M2008:` to something shorter like `M208:`

The other error about the `*********` string is just that `*********` is not a valid AWL instruction. You may have intended a comment. That would have to be written as `// **********`.
