### ISSUE TITLE
Support indirect addressing

### ISSUE THREAD

**Issue by CapacitorSet** [mbuesch/awlsim#4]
For example, `L P#I0.0` loads the address of `I0.0`.

Source: http://www.plcdev.com/siemens_s7_indirect_addressing

**Comment by mbuesch** [comment]
That already is implemented. The syntax is to put a white space between the area and the address. S7 5.5 does it in a similar way.

```
L P#I 0.0
```

We could add support for non-space'ish convenience to pointer format operators, too, like we already do for some non-pointer memory operands. But currently we don't have that.

**Comment by CapacitorSet** [comment]
Oh, sorry, I'm not practical with AWL so I don't know the different nuances in syntax. I'll close the issue, then.

Anyway, *great* job on this project! Unfortunately I can't contribute at this time, but I really appreciate it.

**Comment by mbuesch** [comment]
Support for this has been implemented in 3f29d5dec66fe4558f333c38a1b7f1357426aa02
This will be included in awlsim-0.46.
